app/views/regions/v1/activate.html
app/views/regions/v1/add-another-email-check.html
app/views/regions/v1/add-another-email.html
app/views/regions/v1/add-email.html
app/views/regions/v1/add-organisation.html
app/views/regions/v1/check-and-send.html
app/views/regions/v1/organisation-details.html
app/views/regions/v1/organisation.html
app/views/user-admin/v4/_header.html
app/views/user-admin/v4/add-user.html
app/views/user-admin/v4/change.html
app/views/user-admin/v4/check.html
app/views/user-profile/v2/_header.html
app/views/user-profile/v2/name.html

These should all be outside the `<main>` tag, so they can be skipped when using the "skip to main content" link.
Currently this means manually adding some margin above each Back link. This might be fixed upstream in future by https://github.com/nhsuk/nhsuk-frontend/pull/964

Move back links

---

app/views/regions/v1/add-email.html

Hint text for the email address field.
'Must be a personal email account (not shared).'

Removed reference to lead users and included hint text

---

gulpfile.js

Applies the changes from https://github.com/nhsuk/nhsuk-prototype-kit/pull/329 to enable errors to be shown in the Terminal rather than being swallowed up.
Thanks to @Fenwick17 for spotting this!

Log errors to terminal

---

app/routes/user-admin.js
app/views/user-admin/v4/_reactivation-email.html
app/views/user-admin/v4/_welcome-email.html
app/views/user-admin/v4/check.html
app/views/user-admin/v4/index.html

Following a great suggestion from Ileri, this updates the logic when adding a new user with the same email address as a deactivated user (maybe you forgot they were previously at your organisation, and didn't check the list).
Previously this would show an error message:
The updated flow will let you continue instead, and makes it clear on the confirmation page that you're reactivating a previous user rather than creating a new one.
The existing user will also be updated if the permission level, clinician status or name was changed.

Update logic if adding a deactivated user

---

app/views/user-admin/v4/change.html

Thanks to Jason for suggesting this - users may need to be deactivated for reasons other than having left the organisation, eg having moved to a different area of the same organisation.

Update deactivate question text

---

app/data/session-data-defaults.js
app/routes/user-admin.js
app/views/user-admin/v4/change.html
app/views/user-admin/v4/deactivate.html

This adds some logic so that:
* users cannot deactivate their own account if they are the only active lead administrator for their organisation
* if there are other active lead administrators, they can deactivate their own account, and the content is slightly changed
* after deactivating your own account, you are signed out and return to the homepage

Allow users to deactivate themselves

---

app/data/session-data-defaults.js
app/routes/regions.js
app/views/index.html
app/views/regions/v1/index.html
app/views/regions/v1/organisation.html
app/views/regions/v1/uninvite.html
app/views/reports/download.html
app/views/reports/v5.html
app/views/reports/v6.html
app/views/reports/v7.html

This adds an additional feature to the regions interface which would allow them to 'uninvite' a user, for example if accidentally inviting the wrong person.
Only users who have never signed in to the service could be uninvited. Users who have accessed the service would have to be deactivated by their organisation instead (as we may need to keep their user record for reporting and auditing purposes).
If user is uninvited who is the only user left who had been invited to that organisation, then the organisation itself is also removed. This avoids 'empty' organisations remaining in the organisations list, which may have been the wrong organisation invited.

Allow regions to uninvite users

---

app/views/user-profile/v2/index.html

Updates permission level description on the user profile page. Also updates the list of lead administrator (displayed only if you are not a lead administrator yourself) to use bullets, and be dynamic based on data.

Fix permission description in user profile

---

app/data/session-data-defaults.js
app/routes/reports.js
app/views/reports/choose-data.html

All checkboxes for the data should start off selected, and then users can un-select any data they don't need.
If all options are unselected, they'd get an error:

Default to all data option selected in Reports

---

app/data/session-data-defaults.js
app/locals.js
app/routes/auth.js
app/views/select-organisation.html
app/views/user-profile/v2/index.html

This updates the profile page to show the user the name and address of the organisation they are signed in as.
This is mainly for the benefit of any users who may have multiple accounts with different organisations.
The address is shown as well as the organisation name, as some organisations have identical names, particularly community pharmacies (where there are hundreds with the name "Boots" or "Superdrug").

Display organisation name and address in profile

---

app/routes/vaccines.js
app/views/vaccines/add-batch-to-site-check.html
app/views/vaccines/add-batch-to-site.html
app/views/vaccines/add-batch.html
app/views/vaccines/check.html
app/views/vaccines/edit-batch.html

Since the update to version 9 of NHS Frontend, dates are now easier to retrieve and set.
This means that the `items` array no longer needs to be set on the date inputs, and instead a `values` object can be set at the top level.
When retrieving date parts, these can now be accessed using `data.batchExpiryDate.year` instead of `data['batchExpiryDate-year']`.
When using the [`isoDateFromDateInput` filter](https://x-govuk.github.io/govuk-prototype-filters/date/#isodatefromdateinput), this no longer needs to be given the prefix, and can instead be passed the whole date object.
Before:
```njk
{{ data | isoDateFromDateInput("batchExpiryDate") | govukDate }}
```
After
```njk
{{ data.batchExpiryDate | isoDateFromDateInput | govukDate }}
```

Update (and fix) date handling

---

app/data/session-data-defaults.js

These were previously UPPERCASE as I copied from [ODS](https://odsportal.digital.nhs.uk) which has them all as uppercase. 😞 
In production we’ve decided to apply a filter to auto-capitalise them to make them easier to read, so I've done the same here.

Capitalise site names and addresses

---

app/data/session-data-defaults.js

This sets up the prototype with some default dummy data so that there are 5 vaccine products added with different numbers of products across two sites:

Add some default vaccines across 2 sites

---

app/views/vaccines/index.html

This tweaks site "sites" filter on the Vaccines page, so that:
* the label changes from 'Site' to 'Show'
* the default 'Please select' changes to 'All site'
* it only shows if there are more than 4 sites added
* there's a bit more spacing around it
(Note: the actual filter doesn't yet work in the prototype)
| 4 sites | 5 sites |
| ------- | ------- |
| ![vaccines-4-sites](https://github.com/user-attachments/assets/237ea652-e4d6-4a59-bd05-563ca177878d) | ![vaccines-with-5-sites](https://github.com/user-attachments/assets/ed518b5b-4822-45cd-a0d5-cd65d5b12153) |

Tweak filter on vaccines page

---

app/routes/reports.js
app/views/reports/choose-dates.html

It makes sense to go up to 31 days, so that users can download a full calendar month (for months with 31 days).
| Before | After |
| -------| ----- |
| <img width="691" alt="Screenshot 2024-09-25 at 16 14 38" src="https://github.com/user-attachments/assets/f72f530a-a8d7-4107-9515-89b35f60735a"> | <img width="696" alt="Screenshot 2024-09-25 at 16 11 22" src="https://github.com/user-attachments/assets/a82c9a59-388a-4d3e-a588-eb04f345b19e"> |

Increase reports max date range to 31 days

---

app.js
app/assets/sass/main.scss
app/components/pagination/README.md
app/components/pagination/_pagination.scss
app/components/pagination/macro.njk
app/components/pagination/template.njk
app/data/session-data-defaults.js
app/routes/user-admin.js
app/routes/vaccines.js
app/views/user-admin/index.html
app/views/vaccines/product-page.html
gulpfile.js

This adds a pagination component to the bottom of the Manage users page, rather than just displaying all users on a single page.
The number of users per page is set at 20, although this could be tweaked.
The pagination component is not yet part of the NHS design system, so I’ve borrowed the GOV.UK one and applied NHS styling.  This is still work-in-progress, and I’m working on contributing this to the NHS design system here: https://github.com/nhsuk/nhsuk-frontend/pull/1026
| First page | Middle page | Last page |
| ------ | ------ | ------ |
| ![manage-users-page-1](https://github.com/user-attachments/assets/79f2e200-f771-4327-bc60-e4e30f706d09) | ![manage-users-page-3](https://github.com/user-attachments/assets/635e8a69-72ab-4f93-8fba-623d484cb225) | …

Add pagination to Manage users and Vaccine batches

---

package-lock.json
package.json

Main difference is a change in alignment in the header for the nav.

Update NHS Frontend to 9.1.0

---

app/assets/sass/components/_panel.scss
app/assets/sass/main.scss
app/routes.js
app/routes/vaccinate.js
app/views/includes/header-logged-in-organisation.html
app/views/vaccinate/batch.html
app/views/vaccinate/check.html
app/views/vaccinate/delivery-team.html
app/views/vaccinate/done.html
app/views/vaccinate/eligibility.html
app/views/vaccinate/index.html
app/views/vaccinate/injection-site.html
app/views/vaccinate/no-search-result.html
app/views/vaccinate/patient-estimated-due-date.html
app/views/vaccinate/patient-history.html
app/views/vaccinate/patient-search.html
app/views/vaccinate/patient.html
app/views/vaccinate/search-result.html
app/views/vaccinate/vaccinator.html
app/views/vaccinate/vaccine.html

This adds a first version of a new 'record vaccinations' flow within the service.

Design Sprint 2: New flow for recording vaccinations

---

app/views/vaccinate/check.html

Moves all the answers to the Vaccination section so that there’s a clearer separation between editable and non-editable fields.

Update check answers page

---

app/views/button-states.html

I think it's better for the 'Saving' message to be 'polite' but the error message to be 'assertive' - however we will test this.

Switch ARIA live roles around

---

app/routes/vaccinate.js
app/views/vaccinate/patient-estimated-due-date-pertussis-warning.html
app/views/vaccinate/patient-estimated-due-date-rsv-warning.html
app/views/vaccinate/patient-estimated-due-date.html

This adds some error messages if the estimated due date is highly likely to be an error, and some warnings if the estimated due date is outside the recommended period, but still possible.
This is an error as also highly unlikely to know they are pregnant at this point
This is an error as almost no pregnancies will go beyond 44 weeks
These are shown on a subsequent page, and users can choose to either continue, go back (eg to fix a mistake) or cancel the vaccination (by navigating away).
This is only shown if the patient is not yet 28 weeks pregnant
This is only shown if the patient is not yet 16 weeks pregnant

Add errors and warnings based on estimated due date

---

app/routes/vaccinate.js
app/views/vaccinate/add-batch.html
app/views/vaccinate/batch.html
app/views/vaccinate/check.html

This lets users add a vaccine batch as part of the 'Record vaccination' flow.
Only users with 'admin' or 'lead admin' permission would be able to do this - others would not see the 'Add a batch' option.

Allow users to add a batch as part of the flow

---

app/views/vaccinate/patient-history.html

Ahead of user testing, added a COVID-19 record for 1 December 2024 to vax history - to help make sense of the warning msg that appears if you had a COVID-19 vax less than 3 months ago.

Update patient-history.html with extra covid record

---

app/views/vaccinate/patient-history.html

Changed the text explaining what the history show from: 'This is not a complete vaccination history. It only includes records of COVID-19, flu, pertussis and RSV vaccinations given on the NHS. Note that if an RSV or pertussis vaccination was given at a GP practice, the record will not appear here.' To:
'This shows NHS vaccinations given in England. Currently it includes COVID-19, flu, pertussis and RSV vaccinations. However, if a pertussis or RSV vaccination was given at a GP practice, it will not show here.'

Update vax history explanation on patient-history.html

---

app/routes/vaccinate.js
app/views/vaccinate/check.html
app/views/vaccinate/consent.html

This adds some error messages shown on the consent page and also adds the consent type to the Check your answers page.

Add consent error messages and tweak Check your answers page

---

app/views/vaccinate/check.html

On Check and confirm screen, changed POA consent wording to 'Person with power of attorney for health and welfare' and changed 'Location' label (used for care model) to 'Location type'

Changed POA consent words and location type

---

app/views/vaccinate/check.html

This merges the 2 vaccine answers, vaccine type and product name, into a single 'row' within the check-answers page.
This is because they’re conceptually related and both relate to the 'vaccine', and they’re asked on the same page, so only a single 'change' link is needed.
| Before    |  After |
|----|----|
| <img width="681" alt="Screenshot 2025-02-04 at 12 28 21" src="https://github.com/user-attachments/assets/d3b28e11-cd8f-46cd-8ab2-76d9fe70a929" /> | <img width="667" alt="Screenshot 2025-02-04 at 12 28 01" src="https://github.com/user-attachments/assets/5b8b8733-d891-4f06-9a47-7e382a9d7cb7" /> |

Merge vaccine rows in check answers

---

app/views/layout.html
app/views/vaccinate/batch.html
app/views/vaccinate/check.html
app/views/vaccinate/consent.html
app/views/vaccinate/delivery-team.html
app/views/vaccinate/done.html
app/views/vaccinate/eligibility.html
app/views/vaccinate/index.html
app/views/vaccinate/injection-site.html
app/views/vaccinate/location.html
app/views/vaccinate/no-search-result.html
app/views/vaccinate/patient-estimated-due-date-pertussis-warning.html
app/views/vaccinate/patient-estimated-due-date-rsv-warning.html
app/views/vaccinate/patient-estimated-due-date.html
app/views/vaccinate/patient-history.html
app/views/vaccinate/patient-search.html
app/views/vaccinate/patient.html
app/views/vaccinate/search-result.html
app/views/vaccinate/vaccinator.html
app/views/vaccinate/vaccine.html
app/views/vaccinate/warning.html

This sets the `<title>` tag for all the pages in the new vaccination journey. This is displayed on the browser Tab or window, as well as in bookmarks, and is important for accessibility.
The format is:
`Page name - NHS Record a vaccination`
Generally they match the h1 but sometimes can be shorter, and should avoid including patient details.

Set page titles

---

app/data/session-data-defaults.js
app/routes/vaccinate.js

We’ve decided to default this question to 'Yes', as NHS number is used around ~90% of the time, and so it saves a click.
This also is very low-risk as even if someone doesn’t realise the default has been set, if they click Continue without entering an NHS number there will be an error.
See https://nhsd-jira.digital.nhs.uk/browse/RAVS-1573

Default NHS number known to 'yes'

---

app/routes/vaccinate.js
app/views/vaccinate/check.html
app/views/vaccinate/consent.html

Following user research, we’ve decided to add a 'relationship to the patient' field back in where the consent is based on lasting power of attorney or a court appointed deputy.
We’ve also update the wording slightly:
* Person with power of attorney for health and welfare => Person with lasting power of attorney for health and welfare
* Mental capacity advocate => Independent mental capacity advocate
Jira card: https://nhsd-jira.digital.nhs.uk/browse/RAVS-1546

Update consent screen

---

app/views/vaccinate/add-batch.html
app/views/vaccinate/batch.html
app/views/vaccinate/consent.html
app/views/vaccinate/delivery-team.html
app/views/vaccinate/eligibility.html
app/views/vaccinate/index.html
app/views/vaccinate/injection-site.html
app/views/vaccinate/location.html
app/views/vaccinate/patient-estimated-due-date-pertussis-warning.html
app/views/vaccinate/patient-estimated-due-date-rsv-warning.html
app/views/vaccinate/patient-estimated-due-date.html
app/views/vaccinate/patient-history.html
app/views/vaccinate/vaccinator.html
app/views/vaccinate/vaccine.html
app/views/vaccinate/warning.html

Have updated page titles for the Record journey. The default format we have agreed on for now is "H1 - NHS Record a vaccination"
Most page titles are now aligned with the H1, with these exceptions: 
- Patient details (have kept it a bit shorter)
- Any screen mentioning patient name (the page title will say 'patient' instead of the name)
- Warnings (have done shorter titles as the actual H1s are long and contain personal info)

Update page titles

---

app/views/vaccinate/patient-estimated-due-date-rsv-warning.html

In keeping with changes to other warnings, have changed H1 from 'Are you sure you want to continue' to a more specific msg, in this case 'Patient name is not yet 28 weeks pregnant'. 
Plus changed button text to 'Continue anyway'

Update H1 and button text on RSV warning

---

app/views/vaccinate/eligibility.html

Changed 'Social worker' to 'Social care worker', as the meaning is different (it's social care worker in live RAVS).
Added hint text to explain you can select more than 1 (as this is a change from current live screen) and also to explain that only 1 answer is sent to NHS England.

Updates to eligibility

---

app/views/vaccinate/warning.html

Changed H1 to 'Patient name had a COVID-19 vaccine less than 3 months ago'
Move info about the date they had the vaccine into main body of the screen. 
Changed button text to 'Continue anyway'

Changes to covid interval warning

---

app/views/find-a-record/check.html

Previously was displaying `Invalid DateTime` as the date.

Fix rendering of due date on find-a-record check screen

---

app/routes/find-record.js
app/views/find-a-record/batch.html

Previously, trying to change a batch would take you to the wrong URL, causing the data to become invalid.
N.B this will allow you to change the batch number, but the expiry date will not change

Enable functionality for changing batch number

---

app/routes/vaccinate.js
app/views/find-a-record/patient-history.html
app/views/vaccinate/patient-history.html

This displays the patient’s age on the Check patient page:
It also shows the patient history again when doing the 2nd vaccination for the same patient (co-admin).
🗂️ [Jira card](https://nhsd-jira.digital.nhs.uk/browse/RAVS-1544)

Add age to patient details and show patient history again when doing co-admin

---

app/views/vaccinate/patient-history.html

Update to reflect that RSV vax given at GPs now do show on vax history.

Update to vax history explainer text on patient details screen

---

app/views/vaccinate/empty.html

Updated text. This version can be used for any user, irrespective of permissions. 
This example is for when a user tries to record when there is no-one at their org with 'clinician' status. 
There are 2 other variations of the wording on this screen: for when no vax have been added, and for when no vax AND no clinician have been added.

Updated text for 'Before you start' screen

---

app/views/user-admin/add-user.html

Changed email address label from 'NHS email address' to 'NHS-approved email address'. 
Added text below the H1 to flag that you can only add users with an NHS-approved email address, plus link to the list of approved domains.

Change email address section of Add user page

---

app/routes/apply.js
app/views/apply/check.html
app/views/apply/contact-details.html

We can ask users if they are a registered clinician when signing up, to save them having to set this later (which some users have not realised they need to do).

Add clinician status to onboarding flow

---

app/views/vaccines/edit-batch.html

Added text to help user understand that when you edit a batch, the changes will only apply to records completed in future. The changes to the batch details are not applied retrospectively to records that included the batch in question.

Added explainer para below H1

---

app/data/users.js
app/routes/record-vaccinations.js
app/routes/regions.js
app/routes/support.js
app/routes/user-admin.js
app/views/record-vaccinations/vaccinator.html
app/views/regions/_email-preview.html
app/views/reports/choose-data.html
app/views/support/organisations/add-user.html
app/views/support/organisations/show.html
app/views/support/users/edit-organisation.html
app/views/support/users/show.html
app/views/user-admin/add-user.html
app/views/user-admin/change.html
app/views/user-admin/check.html
app/views/user-admin/deactivated.html
app/views/user-admin/index.html
app/views/user-admin/reactivate-all.html

We’ve decided to change the "Clinician" permission boolean, which controls whether that user can be selected as the vaccinator, to "Vaccinator".
This is because in some settings, those who are not registered clinicians can give vaccinators, such as healthcare assistants.

Changed 'clinician' to 'vaccinator'

---

app/routes/regions.js
app/views/regions/add-vaccines.html
app/views/regions/organisation.html

This updates the design done in #365 to make a small change in that we’ve decided to only allow regions to _add_ the ability for organisations to record individual vaccine types, but not to _remove_ access.
This is because:
* an organisation might need to edit (or correct by deleting and re-adding) a record for a vaccine even if they're no longer giving it
* organisations are able to add records retrospectively if needed
* we don’t want to encourage regions to unnecessarily remove access to vaccines 'out of season' (ie in the summer) when an organisation is likely to need access again in the winter
| Before | After |
| -------|-------|
| ![Screenshot 2025-07-03 at 14 47 46](https://github.com/user-attachments/assets/3c972b1a-155d-4131-99b0-417552f79c1d) | ![Screenshot 2025-07-03 at 14 47 …

Allow regions to only add vaccines to orgs, not remove

---

app/routes/record-vaccinations.js
app/views/record-vaccinations/location.html

This updates the prototype so that:
* location is no longer asked for flu vaccinations
* for COVID-19 vaccinations, the number of options has been reduced to 4
| Before | After |
|--------|-------|
| <img width="775" height="622" alt="Screenshot 2025-07-15 at 14 27 55" src="https://github.com/user-attachments/assets/459a32c3-e2d2-43ee-89a5-262b84bff926" /> | <img width="767" height="499" alt="Screenshot 2025-07-15 at 14 27 37" src="https://github.com/user-attachments/assets/a97b119c-da66-4a7e-8ad0-9daf7eaf1b0e" /> |

Locations screen updates for flu for winter 2025-2026

---

app/views/record-vaccinations/patient-history.html

This adds examples of all 6 supported vaccines to the patient history.
For MMR, we could also display whether it is a first or second dose.

Add more examples of other vaccines to patient history

---

app/data/organisations.js
app/routes/support.js
app/views/support/organisations.html
app/views/support/organisations/add-vaccines.html
app/views/support/organisations/show.html
app/views/support/region.html

This is basically adding the same interface to Support as we've now got in the Regions interface, ie allowing vaccine types to be enabled for organisations (but not removed).
See https://nhsd-jira.digital.nhs.uk/browse/RAVS-2555

Add enable vaccines to support interface

---

app/views/records/batch.html
app/views/records/choose-product.html

Changed 'Which batch was used?' to 'Which batch was it?' (consistent with the retrospective journey)
And added 'product' to the H1 for editing the product. So the H1 is now: Which ((vaccination type)) vaccine product was it?

Changed H1 and page title on batch and product screens

---

app/views/record-vaccinations/mmr/warning-age-old.html
app/views/record-vaccinations/mmr/warning-age-young.html
app/views/record-vaccinations/mmr/warning-dose.html
app/views/record-vaccinations/mmr/warning.html
app/views/record-vaccinations/ppv/warning-age-young.html
app/views/record-vaccinations/ppv/warning.html

Amended page titles for all the MMR and pneumo warnings. 
Amended age, removing days, for the age-related warnings. 
Made some other small content changes to align wording on age more closely with the NHS content guide.

Changes to pneumo and MMR warnings

---

app/routes/record-vaccinations.js
app/views/record-vaccinations/check.html
app/views/record-vaccinations/injection-site.html

Reverting this question back to how it was. Changing:
- Where did you give the vaccination?' back to 'Where did you give the injection?'
- 'Body part' heading above 'Somewhere else' options back to 'Injection site'

Changes to injection site question

---

app/views/updates/multiple.html

This swaps out our previous use of the Notification banner from GOV.UK Frontend with the new one from NHS.UK Frontend.

Switch to new Notification banner from NHS Frontend

---

app.js
app/assets/sass/main.scss
gulpfile.js
package-lock.json
package.json

These are no longer needed as the secondary navigation component has been copied in.
Removing it means we no longer need to import govuk-frontend.

Remove x-govuk prototype components
