NHSDigital/record-a-vaccination-prototype

app/views/grid/standard-header.html, app/views/grid/standard.html, app/views/grid/wider.html, app/views/index.html, app/views/layout-header-nav.html, app/views/layout-wider.html
Some quick grid options based on NHS Design System.
=> grid options

app/assets/sass/main.scss, app/views/layout-header-nav.html
=> Make header nav left aligned

lib/utils.js
See https://github.com/nhsuk/nhsuk-prototype-kit/pull/289
=> Remove redundant console.log

app/views/regions/v1.html, app/views/regions/v1/add-email.html, app/views/regions/v1/add-organisation.html, app/views/regions/v1/check-and-send.html
Thanks to @Deepatee for reviewing.
=> Content tweaks to onboarding journey.

app/routes.js, app/views/regions/v1/_email-preview.html, app/views/regions/v1/add-another-email-check.html, app/views/regions/v1/add-another-email.html, app/views/regions/v1/check-and-send.html, app/views/regions/v1/organisation.html
This makes it possible to add additional lead users to an organisation.
=> Add ability to add invite multiple lead users

gulpfile.js
These are watched by a separate task.
See https://github.com/nhsuk/nhsuk-prototype-kit/pull/302
=> Stop watching scss files

app/assets/sass/components/_header.scss, app/routes.js, app/views/index.html, app/views/user-admin/v2/_header.html, app/views/user-admin/v2/add-user.html, app/views/user-admin/v2/check.html, app/views/user-admin/v2/index.html
This version uses checkboxes for permissions instead of radios
=> Add user admin v2

app/views/user-admin/v1/add-user.html, app/views/user-admin/v2/add-user.html
Make the user permissions a bit more explicit with some additional hint text.
=> Tweak user role permissions

app/assets/sass/components/_header.scss, app/data/session-data-defaults.js, app/filters.js, app/routes.js, app/views/user-admin/v1/change-role.html, app/views/user-admin/v1/index.html, app/views/user-admin/v2/change-permissions.html, app/views/user-admin/v2/check.html, app/views/user-admin/v2/index.html, package-lock.json, package.json
Update content, allow roles/permissions to be editable, and display them properly in list view.
=> Update user admin

app/views/errors/500.html, app/views/index.html
Add HTML version of service unavailable page
=> Add service unavailable page

app/views/errors/500.html
Thanks to @Deepatee for spotting: https://github.com/NHSDigital/record-a-vaccination-prototype/pull/23#issuecomment-2178370964
=> Use you’re not you are

app/routes.js
This is the address for Manchester University NHS Foundation Trust.
=> Update NHS Trust address

app/routes.js
=> Update address in 2 more places

app/data/session-data-defaults.js, app/routes.js, app/views/index.html, app/views/user-admin/v4/_header.html, app/views/user-admin/v4/add-user.html, app/views/user-admin/v4/change.html, app/views/user-admin/v4/check.html, app/views/user-admin/v4/index.html
This version reduces down the clinical status of the user to a binary "are they a clinician? Yes / No", rather than having to specify a clinician type (doctor, nurse, midwife, and so on).
=> Add user admin v4

app/views/user-admin/v4/add-user.html
=> Tweak wording of clinician question

app/routes.js, app/views/index.html, app/views/user-profile/v2/_header.html, app/views/user-profile/v2/index.html, app/views/user-profile/v2/name.html
Changes:
* removed clinician type
* removed professional body number
* removed ability to update email address (for now)
=> User profile version 2

app/views/index.html, app/views/user-onboarding/v3/_header-signed-in.html, app/views/user-onboarding/v3/index.html, app/views/user-onboarding/v3/okta-account-created.html, app/views/user-onboarding/v3/okta-email.html, app/views/user-onboarding/v3/okta-set-password.html, app/views/user-onboarding/v3/okta-sign-in.html, app/views/user-onboarding/v3/sign-in.html, app/views/user-onboarding/v3/signed-in.html
Another version, this time without asking for professional body number and a more realistic Okta flow.
=> Add user onboarding flow with Okta

app/views/regions/v1/index.html
=> Removed reference to lead user

app/views/regions/v1/_email-preview.html
Personalise the email by the user's first name (not org).
=> Included acronym and examples of all vaccines.

app/views/regions/v1/organisation-details.html
Removed checked and confirm, so user isn't prompted to do so.
=> Renamed header

app/data/session-data-defaults.js, app/routes.js, app/routes/vaccines.js, app/views/vaccines/_header.html, app/views/vaccines/add-batch.html, app/views/vaccines/check.html, app/views/vaccines/choose-site.html, app/views/vaccines/choose-vaccine.html, app/views/vaccines/index.html
Getting the main flow of the 'add vaccine' section working (I hope).
=> Get vaccines section working

app/routes/vaccines.js, app/views/user-admin/v4/_header.html, app/views/vaccines/add-batch-to-site-check.html, app/views/vaccines/add-batch-to-site.html, app/views/vaccines/add-batch.html, app/views/vaccines/choose-vaccine.html, app/views/vaccines/deplete-batch.html, app/views/vaccines/index.html, app/views/vaccines/product-page.html
This adds the functionality to add additional batches for a vaccine, edit batches and mark batches as depleted.
=> Update the Manage vaccines flow

app/views/regions/v1/_email-preview.html, app/views/regions/v1/index.html
=> Update regional UI

app/data/session-data-defaults.js, app/views/user-profile/v2/index.html, app/views/user-profile/v2/name.html
List the lead administrators (unless you are a lead administrator)
=> Update user profile page

app/views/contact-us.html, app/views/layout.html
Adding this as a reference for the devs to use.
=> Add contact us page

app/routes.js, app/routes/prototype-admin.js, app/views/layout.html, app/views/prototype-admin/reset-data.html
This is based on a feature in the GOV.UK Prototype Kit, and just makes it easier to reset the data entered.
=> Add button to reset data

app/routes/user-admin.js
Thanks @Deepatee for spotting.
=> Use contraction in error message

app/views/user-onboarding/v1/okta-check-email.html, app/views/user-profile/v2/index.html
We can link to this, now we've added it to the prototype.
=> Link to contact us page

app/routes/vaccines.js, app/views/regions/v1/uninvite.html, app/views/vaccines/deplete-batch.html, app/views/vaccines/index.html, app/views/vaccines/product-page.html
=> Deplete batch

app/routes/reports.js, app/views/reports/check.html, app/views/reports/choose-data.html, app/views/reports/choose-dates-2.html, app/views/reports/choose-site-2.html, app/views/reports/choose-vaccines-2.html, app/views/reports/v7.html
Update the reports interface to use checkboxes to allow users to select groups of data columns to include within their reports.
=> Reports update

app/routes.js, app/routes/auth.js, app/views/home.html, app/views/includes/header-logged-in-organisation.html, app/views/includes/header-logged-in-region.html, app/views/includes/header-logged-in-support.html, app/views/index.html, app/views/okta-sign-in.html, app/views/select-organisation.html
A design for enabling users who belong to multiple organisations to choose which one they want to sign in with when they sign in.
🗂️ [Jira card](https://nhsd-jira.digital.nhs.uk/browse/RAVS-473)
=> Sign in with multiple organisations

gulpfile.js
See https://github.com/nhsuk/nhsuk-frontend/pull/1013
=> Fix gulp assets

app/views/reports/choose-dates.html
spotted that these reference a conditional which isn't defined, by mistake.
=> Remove redundant code

.devcontainer/devcontianer.json
Copied from https://github.com/nhsuk/nhsuk-prototype-kit/pull/428 for testing.
=> Add Devcontainer for GitHub Codespaces

.devcontainer/devcontianer.json
Comments aren't allowed in the JSON.
=> Remove comments from devcontainer JSON

gulpfile.js
See https://github.com/nhsuk/nhsuk-prototype-kit/pull/347 (thanks @edwardhorsford)
=> Parse port as int

.devcontainer/devcontainer.json
Turns out the comments aren’t an issue. See https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#editing-the-devcontainerjson-file
=> Restore comments

app/views/vaccinate/patient-history.html
Adds the screening considerations content from the live service.
Closed:
Opened:
=> Add screening considerations for COVID

app/views/vaccinate/patient-estimated-due-date.html
=> Set example estimated due date to the future

app/views/vaccinate/patient-search.html
A reminder to use the details registered at the GP.
=> Add patient search help text

app/assets/sass/components/_button.scss, app/views/button-states.html
This adds a demo of how button states could work.
Before pressed:
When pressed:
If there’s an error (message would vary depending on error type):
=> Add button states

app/views/vaccinate/check.html, app/views/vaccinate/consent.html, app/views/vaccinate/patient-estimated-due-date.html
Also adds consent to the check your answers page:
=> Consent screen fixes

app/views/vaccinate/batch.html, app/views/vaccinate/check.html, app/views/vaccinate/location.html, app/views/vaccinate/patient.html
This is needed for covid and flu only at the moment, for payment and reporting purposes.
=> Add vaccination location

app/views/button-states.html
Minor changes to the error msgs for 500 ad 503 errors.
=> Update error msgs for button-states.html

app/views/signed-out.html
Changed H1 to 'Record a vaccination' and changed 'You are not signed in.' to 'You are not logged in.'
=> Changes to signed-out.html

app/routes/vaccinate.js, app/views/vaccinate/index.html, app/views/vaccinate/vaccinator.html, app/views/vaccinate/vaccine.html
This adds some validation and error messages. Not all screens done yet, but it’s a start.
=> Add some basic validation errors

app/assets/sass/components/_table.scss, app/routes/regions.js, app/views/regions/v1/delete-organisation.html, app/views/regions/v1/index.html
This adds the ability for regions to delete organisations.
=> Regional interface changes

app/views/vaccinate/warning.html
Changed question to 'Are you sure you want to continue' and added a para break before the link.
=> Update covid-19 interval warning.html

app/routes/vaccinate.js, app/views/vaccinate/add-batch.html, app/views/vaccinate/eligibility.html, app/views/vaccinate/location.html
Eligibility question should be asked after the batch question for COVID-19, flu and RSV only.
For COVID-19 and flu it should be followed by the location, question, but for RSV the next step is to find the the patient.
=> Fix flow around eligibility question

app/routes/vaccinate.js, app/views/vaccinate/check.html, app/views/vaccinate/eligibility.html
I think I've now got this right...
=> Fix logic for co-admin journey

app/views/vaccinate/patient-history.html
Changed some of the dates and products in the vaccination history. Have tried to reflect what a 75-year old (75 as of August 2024) might have received.
=> Update dates and products in patient-history.html

app/routes/vaccinate.js, app/views/vaccinate/batch.html
Adds an error message if no batch selected:
=> Add batch error message

app/routes/vaccinate.js, app/views/vaccinate/injection-site.html
Adds validation error messages for injection site
=> Add injection site validation

app/views/vaccinate/no-search-result.html
Thanks to @Anna-Sutton for spotting.
=> Fix bug: skip to consent screen if no NHS number

app/views/vaccinate/consent.html
Changed 'Person with power of attorney for personal welfare' to 'Person with power of attorney for health and welfare'.
=> POA-change-consent.html

app/routes/vaccinate.js, app/views/vaccinate/delivery-team.html
Add error message for delivery team (if not selected)
=> Add delivery team errors

app/routes/vaccinate.js, app/views/vaccinate/add-batch.html
This doesn't add the full list of possible errors for the date input, but does add the basic ones for if the fields are empty.
=> Add new batch number error message

app/routes.js, app/routes/find-record.js, app/views/find-a-record/batch.html, app/views/find-a-record/check-changes.html, app/views/find-a-record/check-confirm.html, app/views/find-a-record/check.html, app/views/find-a-record/choose-data.html, app/views/find-a-record/choose-dates.html, app/views/find-a-record/choose-site.html, app/views/find-a-record/choose-vaccines.html, app/views/find-a-record/consent.html, app/views/find-a-record/delete.html, app/views/find-a-record/delivery-team.html, app/views/find-a-record/done.html, app/views/find-a-record/download.html, app/views/find-a-record/eligibility.html, app/views/find-a-record/index.html, app/views/find-a-record/injection-site.html, app/views/find-a-record/patient-estimated-due-date.html, app/views/find-a-record/patient-history-change.html, app/views/find-a-record/patient-history.html, app/views/find-a-record/patient-search.html, app/views/find-a-record/search-result.html, app/views/find-a-record/vaccinator.html, app/views/includes/header-logged-in-organisation.html
This pull request includes a new 'Fidn a record' section within RAVS which allows users to find records in order to be able to do the following to patient records created in RAVS:
- View
- Edit
- Delete
=> Add 'Find a record' section

app/routes/vaccinate.js
Minor edits to a few messages to make the tone and style of messages more consistent and more conversational. For example, changed 'Enter first name' to 'Enter a first name'
=> Error messages edits

app/views/vaccinate/patient-estimated-due-date-pertussis-warning.html
Changed H1 from 'Are you sure you want to continue?' to 'Patient name is xx weeks pregnant'
=> Update H1 and button text on pertussis warning

app/data/session-data-defaults.js, app/routes/find-record.js, app/views/find-a-record/batch.html, app/views/find-a-record/check.html, app/views/find-a-record/choose-dates.html, app/views/find-a-record/choose-vaccines.html, app/views/find-a-record/consent.html, app/views/find-a-record/delete.html, app/views/find-a-record/delivery-team.html, app/views/find-a-record/eligibility.html, app/views/find-a-record/injection-site.html, app/views/find-a-record/patient-estimated-due-date.html, app/views/find-a-record/patient-history.html, app/views/find-a-record/vaccinator.html
Some fixes to get the Edit/Update screens working from session data.
=> Update edit records based on session data

app/views/vaccinate/location.html
Changed this to reflect a change we're making in live (see RAVS-1626)
=> Changed 'Off site outreach even't to 'Outreach event' in location screen

package-lock.json, package.json
=> Remove dev dependencies

app/views/find-a-record/eligibility.html
Corrected a typo and added hint text.
=> Minor edits to eligibility in Find a record

app/routes/vaccinate.js, app/views/vaccinate/check.html, app/views/vaccinate/healthcare-worker.html
This question appears in our current service, when the vaccine is Covid or Flu, and the eligibility reason is "Healthcare worker".
The data is not sent to other services, but we have some evidence that it is used by some NHS trusts for reporting purposes, including to UKHSA.
🗂️ [Jira card](https://nhsd-jira.digital.nhs.uk/browse/RAVS-1505)
=> Add an extra question about Healthcare worker role

app/views/vaccinate/batch.html
Updated the expiry dates on the batches so they are all in the future.
=> Expiry dates updated on batch page

app/views/find-a-record/delete.html
Added a question mark to the end of the heading as it's a question
=> Minor edit to Delete screen in Find a record journey

app/views/find-a-record/delete.html, app/views/vaccinate/patient-estimated-due-date-pertussis-warning.html, app/views/vaccinate/patient-estimated-due-date-rsv-warning.html, app/views/vaccinate/patient-history.html, app/views/vaccinate/refine-search-result.html, app/views/vaccinate/review-previous.html, app/views/vaccinate/warning-wrong-age-for-product.html
Added or edited page titles on 6 screens:
- Review your answers (screen you go to if you do same vax another patient)
- Pertussis warning
- RSV warning
- Product may not be suitable for this age warning
- Refine your search
- Patient details and history
=> Page title additions and edits.html

app/assets/sass/components/_tag.scss, app/assets/sass/main.scss, app/views/includes/header-logged-in-organisation.html
This would be a way for us to highlight that "Record vaccinations" is a new section.
=> Add tag to header nav

app/views/accessibility-statement.html, app/views/vaccinate/empty.html
- Amended 2 links to RAVS, adding 'https://' to start of url
- Amended link to email adding 'mailto:'
- Swapped 'Enforcement procedure' and 'Give feedback' H2s 
- Added a couple of missing para breaks
- Deleted 1 redundant full stop
=> Minor edits to accessibility statement

app/views/find-a-record/delete.html, app/views/layout.html, app/views/terms-of-use.html, app/views/terms-of-use1.html
Includes updates to:
terms of use - short
terms of use - long
Delete record 
https://nhsd-jira.digital.nhs.uk/browse/RAVS-1711
=> Adds terms of use pages

app/views/_feedback-panel.html
This should help, at least in VoiceOver.
More testing required.
=> Feedback panel: Use fieldset and legend to group buttons

app/views/find-a-record/batch.html, app/views/find-a-record/choose-dates.html, app/views/find-a-record/choose-vaccines.html, app/views/find-a-record/consent.html, app/views/find-a-record/delete.html, app/views/find-a-record/delivery-team.html, app/views/find-a-record/eligibility.html, app/views/find-a-record/index.html, app/views/find-a-record/injection-site.html, app/views/find-a-record/patient-estimated-due-date.html, app/views/find-a-record/patient-history.html, app/views/find-a-record/patient-search.html, app/views/find-a-record/vaccinator.html
On Record landing page, changed H1 and page title to 'Records'
=> Add page titles and other minor changes to Records

app/views/vaccinate/empty.html, app/views/vaccinate/empty1.html, app/views/vaccinate/empty2.html
Changed font sizes in empty.html and emply1.html as body copy was too large. Plus created a 3rd file, empty2.html, for the third version of the 'Before you start' message.
=> Before you start recording vaccinations screens

app/views/terms-of-use1.html
6.1.5 changed 'versions' to 'version'
7.3 changed 'Your' to 'your'
8.2 changed 'up-to-date' to 'up to date'
9.4 changed 'We' to 'we'
Also amended date last updated to 27 March 2025
=> Minor edits to long terms of use page

app/views/includes/header-logged-in-support.html, app/views/support/region.html, app/views/support/regions.html, app/views/support/users/edit-region.html, app/views/support/users/show.html
This reduces the support interface to just being able to activate/deactivate regional users, and add new regional users.
=> Reduce support interface to MVP

app/assets/sass/components/_button.scss, app/views/_feedback-panel.html
Also switch to 5 options, and wider buttons.
=> Tweak feedback wording

app/routes/user-admin.js
Changed the error messages as follows:
Enter a first name
Enter a last name
Enter an NHS-approved email address
Email address must be NHS-approved
This email address has already been added
Select a permission level
Select if they’re a clinician
=> Updated error msgs in user-admin.js

app/views/regions/_email-deactivate.html, app/views/regions/_email-reactivate.html
In deactivate email:
Added an extra para break
Changed NHSE to NHS England
Changed second mention of [date] to 'this date'
In reactivate email:
Changed NHSE to NHS England
Changed some <br> to <p>
=> Minor edits to deactivate and reactivate emails in Regional site

app.js
Fix bug introduced accidentally by #286.
=> Bugfix: Add folder for app components

app/views/apply/email-confirmed.html, app/views/apply/email.html, app/views/apply/onboarding0.html, app/views/apply/onboarding3.html, app/views/regions/_email-reject.html, app/views/regions/add-another-email.html, app/views/regions/add-email.html, app/views/regions/awaiting-approval.html, app/views/regions/awaiting-approval1.html, app/views/regions/index.html
Changed 'awaiting' to 'waiting for' on index page
=> Text edits to regional onboarding

app/routes/record-vaccinations.js
Updated a few error messages to make sure they are the same in the prototype and in the dev environment.
=> Updates to error messages in record-vaccinations.js

app/views/record-vaccinations/batch.html, app/views/record-vaccinations/patient-history.html, app/views/record-vaccinations/warning.html
Updated batch expiry dates so they are in the future.
=> Updated batch expiry dates

app/routes/record-vaccinations.js, app/views/record-vaccinations/healthcare-worker.html
Adds missing error message if no healthcare worker role is selected.
=> Add error message for healthcare worker role

app/views/record-vaccinations/delivery-team.html
=> Put delivery teams in alphabetical order

app/views/regions/_email-deactivate.html
Branch created for testing the regional interface for deactivate and reactivating.
=> changes to deactivate email

app/views/apply/check.html, app/views/apply/contact-details.html
Changed hint text for clinician field to:
"We ask this so we can set you up with the right permissions."
=> Update to contact-details.html

app/routes/apply.js, app/views/apply/check-your-email.html, app/views/apply/welcome-email.html
Added more info to the final screen to help users anticipate what's coming next.
=> Add email to Apply journey

app/views/apply/start.html
Changed last bullet about signing up for more than 1 pharmacy. Removed the option to 'contact us' as we agreed that for testing we'd only offer the option of reusing this form.
=> Update to start.html

package-lock.json, package.json
=> Use Node 22 and NPM 11

app/assets/sass/components/_button-group.scss, app/assets/sass/components/_button.scss, app/assets/sass/components/_feedback-panel.scss, app/assets/sass/components/_related-nav.scss, app/assets/sass/components/_table.scss, app/components/pagination/_pagination.scss
This updates the deprecations in NHS 9.5.0 to use the new names, see https://github.com/nhsuk/nhsuk-frontend/releases/tag/v9.5.0
=> Fix deprecations

app/views/record-vaccinations/batch.html, app/views/record-vaccinations/delivery-team.html, app/views/record-vaccinations/vaccine.html
Copied fom #369 after we accidentally merged into the wrong branch 🤦
=> Update guidance content in Details

app/routes.js, app/routes/helpers.js, app/views/layout.html, app/views/prototype-setup.html, app/views/record-vaccinations/vaccine.html, app/views/vaccines/index.html
This adds an action to let you set up batches for all available vaccines in a single click, rather than having to use the interface each time.
=> Add shortcut for setting up vaccines

app/views/record-vaccinations/patient-deceased-stop.html, app/views/record-vaccinations/patient-history.html
Changed page title to 'The patient has died' to reflect H1.
=> Amended page title in patient-deceased-stop.html

app/views/record-vaccinations/eligibility.html, app/views/record-vaccinations/injection-site.html, app/views/record-vaccinations/vaccine.html
Added conditional code so H1 changes if record journey is in the past. See line 97
=> H1 for past version of eligibility, injection and vaccine questions

app/views/record-vaccinations/review-previous.html
=> Update same vaccination different patient

app/components/pagination/_pagination.scss, app/components/pagination/template.njk
=> Pagination tweak

app/views/record-vaccinations/warning-wrong-age-for-product.html, app/views/record-vaccinations/warning.html
Updated the interval and age/product warnings (currently used for covid and flu) to align with slightly amended wording we've agreed for these templates.
=> Update to warnings
